language: "en-US"

reviews:
  tools:
    ruff:
      enabled: true
    flake8:
      enabled: true
    # enable others if needed
  path_filters:
    - "**/*.py"
    - "!**/__pycache__/**"
    - "!accounts.csv"
    - "!data/**"
  # maybe you want to enforce style, docstrings, etc.
  suggested_reviewers: true
  auto_assign_reviewers: false

# optionally, specify instructions for certain paths
path_instructions:
  - path: "main.py"
    instructions: "Focus on IPO-apply logic, error handling, retry behavior, logging, test coverage"

# other settings (strictness, profile etc.)
